Kroskod/KrodAI-Engine

Core/reasoning.py
Add Reasoning System class to implement chain-of-thought reasoning and explanation capabilities. Includes methods for internal reasoning generation, explanation formatting, and reasoning application based on query complexity. Enhanced logging for debugging and performance tracking.
=> Added Reasoning System

interfaces/cli.py
Add Krod CLI for interactive command-line interface to KROD. Includes session management, command history, and configuration handling. Supports query processing and debugging features.
=> Add KrodCLI for interactive command-line interface to KROD.

Core/common_sense.py
class to provide basic knowledge and reasoning capabilities for KROD. Im still adding code.
=> Added CommonSense

Core/common_sense.py
Refactor CommonSense class into CommonSenseSystem with enhanced functionality for assessing query complexity, ambiguity, and response depth. Improved logging and added methods for detailed reasoning capabilities.
=> Refactor CommonSense class into CommonSenseSystem.

Core/engine.py
Into Krod Engine for enhanced query processing. Implement common sense reasoning and clarification checks, with context management for responses.
=> Integrate ReasoningSystem, ClarificationSystem, and CommonSenseSystem

Core/llm_manager.py, Core/token_manager.py
token limit management and usage tracking. Introduced token limit checks before requests and updated usage recording after response generation. Created token_manager.py for handling token management logic.
=> Created Token_Manager integrated it into llm_manager.

Core/engine.py
Implemented important functions KrodEngine with token management and domain-specific modules. Initialize TokenManager, CodeAnalyzer, MathSolver, and LiteratureAnalyzer for improved query processing and knowledge extraction.
=>  Enhanced KrodEngine, removed requirements.txt

modules/code/analyzer.py
Code Analyzer module for handling code-related queries, including language detection, code snippet extraction, and task identification. Implements a structured prompt generation for LLM responses based on user queries and extracted code.
=> Added CodeAnalyzer module

modules/math/solver.py
Module for handling mathematical queries, including equation solving, proofs, and symbolic manipulation. Introduced categories for various mathematical topics and initialized logging for the module.
=> Added MathSolver

modules/math/solver.py
Add Solve Equation for mathematical assistance.
=> Remove unnecessary newline at the end of solver.py

modules/research/literature.py
Add LiteratureAnalyzer module for research query analysis
=> Add Literature Analyze

modules/research/literature.py
For enhanced research query handling.
=> Add citation extraction and processing capabilities to LiteratureAnalyzer

Core/security_validator.py
Add recommendations and disclaimers to Security Validator based on security level, enhancing response transparency and guidance.
=> Add recommendations and disclaimers

Core/engine.py
for enhanced query security validation, including security level assessment, warnings, and disclaimers in responses.
=> Integrate SecurityValidator into KrodEngine

modules/code/algorithm.py
module for algorithm complexity analysis, optimization suggestions, and pattern recognition
=> Add Algorithm Analyzer

modules/code/algorithm.py
Add methods for analyzing algorithm complexity, identifying patterns and suggesting optimizations in Algorithm Analyzer
=> AlgorithmAnalyzer.py

Core/identity.py
Add Krod Identity module to define KROD's identity, capabilities, features, and ethical principles, including methods for retrieving detailed descriptions.
=> Add KrodIdentity module

krod/core/llm_manager.py, krod/main.py
in main.py and expand provider list in LLMManager to include 'deepseek' and 'gemini'.
=> Update environment variable references 

krod/core/llm_manager.py, krod/core/token_manager.py
LLMManager and refactor TokenManager for model-specific limits and thread safety
=> Add default OpenAI configuration 

krod/core/common_sense.py, krod/core/engine.py, krod/core/llm_manager.py, krod/modules/code/algorithm.py, krod/modules/code/analyzer.py
with improved error handling and domain-specific prompts. Default domain set in apply_common_sense method, and response generation updated to use new prompt structure in LLMManager. Refactor AlgorithmAnalyzer and CodeAnalyzer to align with updated response format.
=> Enhance KrodEngine and LLMManager.

krod/core/reasoning.py, krod/interfaces/cli.py
Also adjust command processing in KrodCLI for improved clarity.
=> Remove model_type parameter from reasoning generation

krod/core/llm_manager.py
It Includes detailed structures for chat, greeting, code analysis, optimization, and generation prompts.
=> Enhance LLMManager templates for improved clarity and professionalism in responses.

krod/core/decision.py
This module to implement basic autonomous decision-making capabilities with confidence levels.
=> Add Krod decision system

krod/core/decision.py
For enhanced decision-making capabilities, including decision history tracking and logging.
=> Add DecisionSystem class to Krod

krod/core/engine.py
Enhanced query processing and decision-making capabilities. Implement methods for autonomous processing, clarification handling, and standard processing based on decision confidence levels.
=> Integrate DecisionSystem into KrodEngine

krod/core/engine.py, requirements.txt
add TODO for dynamic module loading in Krod Engine
=> Add FastAPI and related dependencies to requirements.txt; 

.gitignore, krod/interfaces/api.py
Updates api.py for production use.
=> Update and Enhance API logging for production.

krod/core/llm_manager.py, krod/interfaces/api.py, requirements.txt
API for improved functionality
- Added new dependencies to requirements.txt for enhanced LLM capabilities.
- Refactored import statements in llm_manager.py for clarity.
- Improved response formatting in LLM Manager.
- Updated API initialization and added a root endpoint for health check.
=> Update requirements and refactor LLM Manager

.gitignore, krod/core/decision.py, krod/core/engine.py, krod/core/types.py, krod/interfaces/api.py
Refactor Decision class to use DecisionConfidence enum and separate type definitions into types.py; update logging configuration in API module.
=> Fixed some major issue for API production. 

krod/core/engine.py, krod/core/llm_manager.py, krod/interfaces/api.py
Enhance KrodEngine and LLMManager to support conversation history in query processing and response generation. Update API to include conversation history in request model.
=> Enhance modules to support conversations history in query

krod/core/llm_manager.py
LLMManager prompt handling to improve response clarity and context awareness. Updated greeting and farewell prompts for a more natural tone, and enhanced conversation history formatting for technical queries.
=> Refactor llmmanager.py for prompt handling.

krod/core/llm_manager.py, krod/interfaces/api.py
In LLM Manager and API query processing to improve error management and user experience. Enhance logging for better debugging and add constants for request timeouts.
=> Implement timeout handling.

krod/core/engine.py, krod/core/llm_manager.py, krod/interfaces/api.py
And improve error handling in LLMManager. Added validation for response format in API query processing.
=> Enhance KrodEngine's process method to be asynchronous

krod/core/context_store.py
This new module provides functionality for saving and loading session data in a persistent manner, allowing for better management of research context within the Krod system. It includes methods for saving sessions to JSON files and loading them back, with error handling and timestamp conversion for session metadata.
=> Add ContextStore module for session data management.

krod/core/config.py, krod/core/context_store.py, krod/core/research_context.py
Configured context storage in Research Context and config.py. Added a session management.
=> Update and enhance Research_context to configure Context_storage 

.gitignore, krod/core/decision.py, krod/core/engine.py, krod/core/reasoning.py, krod/interfaces/cli.py, krod/main.py
Update .gitignore to include new files and directories, enhance KrodEngine with decision system initialization, and improve logging and error handling in various components. Refactor reasoning process in Krod's reasoning system for better clarity and functionality.
=> fix query problem, Enhance responses. 

krod/core/clarification.py, krod/core/engine.py, krod/modules/code/analyzer.py, krod/modules/general/general_module.py
to check for clarification based on ambiguity levels, and improve CodeAnalyzer response handling for missing code snippets. Refactor general module prompt for better user interaction.
=> Enhance ClarificationSystem prompt formatting for clarity, update KrodEngine

krod/core/engine.py
- When not found, enhancing traceability in the research context management.
=> Improve context handling in KrodEngine by adding logging for context creation

krod/core/engine.py, krod/core/reasoning.py
- Introduced a new `is_greeting` function to identify greetings in user queries, improving interaction handling.
- Updated the `process` method to utilize the new greeting detection logic for early response.
- Enhanced the reasoning system to return both reasoning and final response in a structured format, improving clarity in responses.
=> Add greeting detection to KrodEngine and enhance reasoning response structure
